##
# Copyright (C) 2009 Renê de Souza Pinto
# TempOS - Tempos is an Educational and multi purpose Operating System
#
# Makefile - TempOS Build System
#

PWD := $(shell pwd)


# Default files and dirs
kimage     := tempos.elf
fimage     := floppy.img

conffile   := .config
config_def := scripts/config.default
config_mk  := scripts/Makefile.config
config_h   := include/config.h

objlist    := objs.list

checkarch  := scripts/checkarch.sh

ECHO       := $(shell which echo)


# Default values
CC = gcc
LD = ld
CFLAGS = -Wall

# Compilation tools
DEPTOOL  := scripts/deptool.sh


# Export all variables
export

# Pseudo rules
.PHONY: showtitle clean


all: tempos

showtitle:
	@$(ECHO) " ===================== "
	@$(ECHO) "[ TempOS Build System ]"
	@$(ECHO) " ===================== "


tempos: showtitle config
	@[ -f $(objlist) ] && rm -f $(objlist) || echo " * Sanity check"
	@$(ECHO) -n " * Checking architecture..."
	@$(checkarch) $(conffile)


##
# Read configuration file and generate proper files
#
config: $(conffile)
	@$(ECHO) " + READ $(conffile)"
	 
	@$(ECHO) " + WRITE $(config_mk)"
	@$(ECHO) -e "##\n# This file was automatic generated by TempOS Build System\n# WARNING: Do not edit.\n#\n" > $(config_mk)
	@sed -n "s/ \{0,\}\(\w\+\) \{0,\}= \{0,\}y/\1=y\\nexport \1/gp" $(conffile) >> $(config_mk)
	
	@$(ECHO) " + WRITE $(config_h)"
	@$(ECHO) -e "/**\n * This file was automatic generated by TempOS Build System\n * WARNING: Do not edit.\n **/\n" > $(config_h)
	@$(ECHO) -e "#ifndef TEMPOS_CONFIG_H\n\n\t#define TEMPOS_CONFIG_H\n" >> $(config_h)
	@sed -n "s/ \{0,\}\(\w\+\) \{0,\}= \{0,\}y/\t#define \1/gp" $(conffile) >> $(config_h)
	@$(ECHO) -e "\n#endif /* TEMPOS_CONFIG_H */\n" >> $(config_h)

-include $(config_mk)

##
# Use a default configuration file
#
$(conffile):
	@$(ECHO) "****************************************************************************"
	@$(ECHO) "* WARNING: Kernel build configuration file not found. Use default options. *"
	@$(ECHO) "****************************************************************************"
	@cp $(config_def) $(conffile)


##
# test
#
test: showtitle
	@$(ECHO) -n " * Checking architecture..."
	@[ -f "$(fimage)" ] && ($(checkarch) $(conffile) test) \
		|| (echo -e "\nYou need to build TempOS and generate the disk image first."; \
			echo "Try: make install")


##
# install
#
install: tempos $(fimage)
	@$(ECHO) -n " * Checking architecture..."
	@$(checkarch) $(conffile) install


$(fimage):
	@scripts/mkdisk_img.sh $(fimage)

##
# clean
#
clean: showtitle
	@$(ECHO) "Cleaning..."
	@$(ECHO) -n " * Checking architecture..."
	@$(checkarch) $(conffile) clean
# These rules should stay after architecture clean
	@[ -f $(config_mk) ] && (rm -f $(config_mk) && $(ECHO) " - Remove $(config_mk)") || $(ECHO) " ! $(config_mk) not found."
	@[ -f $(config_h) ] && (rm -f $(config_h) && $(ECHO) " - Remove $(config_h)") || $(ECHO) " ! $(config_h) not found."
	@$(ECHO) done.

