/*
 * This file was automatic generated by TempOS Build System
 * WARNING: Do not edit.
 **/

#ifndef TEMPOS_CONFIG_H

	#define TEMPOS_CONFIG_H

	#define CONFIG_ARCH_X86 y
	#define CONFIG_X86_MAKEFILE "arch/x86/build/Makefile"
	#define CONFIG_SYSTEM_HZ 250
	#define CONFIG_BUFFER_QUEUE_SIZE 1024
	#define CONFIG_FS_EXT2 y

#endif /* TEMPOS_CONFIG_H */

